apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api-deployment
spec:
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
      - name: weather-api
        image: isaacnborges/weatherapi:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80