apiVersion: v1
kind: Service
metadata:
  name: weather-api
  labels:
    app: weather-api
spec: 
  selector: 
    app: weather-api
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30010
      name: http
  type: NodePort